src/Advertproject/PlatformBundleOLD/Entity/Image.php
<?php

namespace Advertproject\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="Advertproject\PlatformBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @var
     *
     */
    private $file;

    private $tempFilename;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if(null === $this->file)
        {
            return;
        }
        //Before recording the entity in the database the attributes url and alt must be hydrated to avoid an error
        $this->url = $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if(null === $this->file)
        {
            return;
        }

        if(null !== $this->tempFilename)
        {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if(file_exists($oldFile))
            {
                unlink($oldFile);
            }
        }

        $this->file->move($this->getUploadRootDir(),
            $this->id.'.'.$this->url
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if(file_exists($this->tempFilename)){
            unlink($this->tempFilename);
        }
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if (null !== $this->url) {
            $tempFilename = $this->url;
            $this->url = null;
            $this->alt = null;
        }
    }

    public function getUploadDir()
    {
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
}

src/Advertproject/PlatformBundleOLD/Form/AdvertType.php
<?php

namespace Advertproject\PlatformBundle\Form;

use Advertproject\PlatformBundle\Entity\AdvertRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AdvertType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',       'text')
            ->add('content',     'ckeditor')
            ->add('image',        new ImageType(), array('required' => false))
            ->add('categories',  'entity', array(
                'class'       => 'APPlatformBundle:Category',
                'property'    => 'name',
                'multiple'    => true,
                'expanded'    => false

            ))

        ;

        $builder
            ->addEventListener(
                FormEvents::PRE_SET_DATA,
                function(FormEvent $event){
                    $advert = $event->getData();
                    if(null === $advert)
                    {
                        return;
                    }
                    if(!$advert->getPublished() || null === $advert->getId())
                    {
                        $event->getForm()->add('published', 'checkbox', array('required' => false));
                    }else{
                        $event->getForm()->remove('published');
                    }
                }
            );
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Advertproject\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'advertproject_platformbundle_advert';
    }
}

src/Advertproject/PlatformBundleOLD/Controller/AdvertController.php
<?php
/**
 * Created by PhpStorm.
 * User: Patrick
 * Date: 5/9/15
 * Time: 8:46 PM
 */

namespace Advertproject\PlatformBundle\Controller;

use Advertproject\PlatformBundle\Bigbrother\BigbrotherEvents;
use Advertproject\PlatformBundle\Bigbrother\MessagePostEvent;
use Symfony\Component\Security\Core\User\UserInterface;
use Advertproject\PlatformBundle\Entity\AdvertSkill;
use Advertproject\PlatformBundle\Entity\Category;
use Advertproject\PlatformBundle\Form\AdvertEditType;
use Advertproject\PlatformBundle\Form\AdvertType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Advertproject\PlatformBundle\Entity\Advert;
use Advertproject\PlatformBundle\Entity\Image;
use Advertproject\PlatformBundle\Entity\Application;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class AdvertController extends Controller
{

    public function indexAction($page)
    {
        if($page < 1)
        {
            throw new NotFoundHttpException("La page ".$page." est inexistante !");
        }

        $nbPerPage = $this->container->getParameter('nb_per_page');

        $listAdverts = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('APPlatformBundle:Advert')
            ->getAdverts($page, $nbPerPage)
        ;

        $nbPages = ceil(count($listAdverts)/$nbPerPage);

        if($page > $nbPages){
            throw new NotFoundHttpException("La page ".$page." est inexistante !");
        }

        return $this->render('APPlatformBundle:Advert:index.html.twig', array(
            'listAdverts' => $listAdverts,
            'nbPages'     => $nbPages,
            'page'        => $page
        ));
    }

    public function defaultAction()
    {
        //$nbPerPage = $this->container->getParameter('nb_per_page');

        /*$listAdverts = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('APPlatformBundle:Advert')
            ->getAdverts($page, $nbPerPage)
        ;

        $nbPages = ceil(count($listAdverts)/$nbPerPage);

        if($page > $nbPages){
            throw new NotFoundHttpException("La page ".$page." est inexistante !");
        }*/

        return $this->render('APPlatformBundle:Advert:index.html.twig');

    }

    public function viewAction($id)
    {

        $repository = $this->getDoctrine()->getManager()->getRepository('APPlatformBundle:Advert');

        $advert = $repository->find($id);

        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'identifiant ".$id." n'a pas été trouvé");
        }

        return $this->render("APPlatformBundle:Advert:view.html.twig", array(
            "advert" => $advert
        ));

        // On récupère l'EntityManager
        //$em = $this->getDoctrine()->getManager();

        // Pour récupérer une annonce unique : on utilise find()
        //$advert = $em->getRepository('APPlatformBundle:Advert')->find($id);

        // On vérifie que l'annonce avec cet id existe bien
        /*if ($advert === null) {
            throw $this->createNotFoundException("L'annonce d'id ".$id." n'existe pas.");
        }*/

        // On récupère la liste des advertSkill pour l'annonce $advert
        /*$listAdvertSkills = $em->getRepository('APPlatformBundle:AdvertSkill')->findByAdvert($advert);

        $listApplications = $em
            -> getRepository('APPlatformBundle:Application')
            -> findBy(array('advert' => $advert))
        ;*/



        // Puis modifiez la ligne du render comme ceci, pour prendre en compte les variables :
        /*return $this->render('APPlatformBundle:Advert:view.html.twig', array(
            'advert'           => $advert,
            'listAdvertSkills' => $listAdvertSkills,
            'listApplications' => $listApplications
        ));*/
    }

    public function listAction()
    {
        $listAdvert = $this
            -> getDoctrine()
            -> getManager()
            -> getRepository('APPlatformBundle:Advert')
            -> getAdvertWithApplications()
        ;

        foreach($listAdvert as $advert)
        {
            $advert->getApplications();
        }
    }


    public function addAction(Request $request)
    {
        /*if(!$this->get('security.context')->isGranted('ROLE_USER'))
        {
            throw new AccessDeniedException('Please create an account to submit an advert');
        }*/

        //On crée un objet Advert
        $advert = new Advert();

        $advert->setAuthor('Patrick Ghislain');
        $advert->setContent('Nous recherchons un développeur Symfony2.');
        $advert->setTitle('Développeur Symfony2');

        //On récupère l'EntityManager
        $em = $this->getDoctrine()->getManager();

        //Etape 1 : on persiste l'entité
        $em->persist($advert);

        // On "flush" tout ce qui a été persisté avant
        $em->flush();

        if ($request->isMethod('POST')) {
            $request->getSession()-> getFlashBag()->add('notice', 'L\'annonce a bien été ajoutée !');

            return $this->redirect($this->generateUrl('ap_platform_view', array('id' => $advert->getId())));
        }

        return $this->render('APPlatformBundle:Advert:add.html.twig');

        //Grâce au service 'form.factory', on crée le formBuilder
        //$form = $this->get('form.factory')-> create(new AdvertType(), $advert);
        //$form = $this->createForm(new AdvertType(), $advert);

        /*if($form->handleRequest($request)->isValid())
        {
            $antispam = $this->container->get('ap_platform.antispam');
            if ($antispam->isSpam($advert->getContent())) {
                throw new \Exception('Votre contenu est trop court !');
            }
            //$event = new MessagePostEvent($advert->getContent(), $advert->getAuthor());

            //Triggering the event
           // $this->get('event_dispatcher')->dispatch(BigbrotherEvents::onMessagePost, $event);

            /*$application1 = new Application();
            $application1->setContent('Je suis intéressé');
            $application1->setAuthor('Jacques');
            $application1->setAdvert($advert);

            $application2 = new Application();
            $application2->setContent('Moi aussi, je suis intéressé');
            $application2->setAuthor('Patrick');
            $application2->setAdvert($advert);*/

            //$em = $this->getDoctrine()->getManager();
            //$em->persist($advert);
           // $em->persist($application1);
            //$em->persist($application2);

            //$em->flush();

            /*$request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée !');

            return $this->redirect($this->generateUrl('ap_platform_view', array('id' => $advert->getId())));
        }

        return $this->render('APPlatformBundle:Advert:add.html.twig', array(
           'form' => $form->createView()
        )); */

    }

    public function editAction($id, Request $request)
    {

        $advert1 = new Advert();
        $advert1->setTitle('Infographiste sur Casablanca pour un CDD');
        $advert1->setContent('Nous recherchons un infographiste pour mission de 3 mois sur Casablanca');
        $advert1->setAuthor('Ghislain');

        $em = $this->getDoctrine()->getManager();
        $advert2 = $em->getRepository('Advertproject\PlatformBundle\Entity\Advert')->find(4);

        $advert2->setDate(new \DateTime());

        $em->persist($advert1);

        $em->flush();

        $request->getSession()->getFlashBag()->add('notice', 'L\'annonce a bien été ajoutée');

        return $this->redirect($this->generateUrl('ap_platform_view', array(
            'id' => $advert2->getId()
        )));

        /*$em = $this->getDoctrine()->getManager();
        $advert = $em
            ->getRepository("APPlatformBundle:Advert")
            ->find($id);

        if(null === $advert)
        {
            throw new NotFoundHttpException("L'annonce ".$id." est inexistante.");
        }

        $form = $this->createForm(new AdvertEditType(), $advert);
        if($form->handleRequest($request)->isValid()){

            // On crée l'évènement avec ses 2 arguments
            $event = new MessagePostEvent($advert->getContent(), $this->getUser());

            // On déclenche l'évènement
            $this
                ->get('event_dispatcher')
                ->dispatch(BigbrotherEvents::onMessagePost, $event)
            ;

            // On récupère ce qui a été modifié par le ou les listeners, ici le message
            $advert->setContent($event->getMessage());

            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Advert updated!');
            return $this->redirect($this->generateUrl('ap_platform_view', array('id' => $advert->getId())));
        }

        return $this->render('APPlatformBundle:Advert:edit.html.twig', array(
            'advert' => $advert,
            'form'   => $form->createView()
        )); */
    }

    public function menuAction()
    {
        $listAdverts = array(
            array('id'=>2, 'title'=>'Développeur Web', 'author'=>'Patrick', 'content'=>'Je cherche un développeur Web pour un projet web bien rémunéré'),
            array('id'=>7, 'title'=>'Offre de stage webdesigner', 'author'=>'Bass', 'content'=>'Je cherche un webdesigner Web pour un stage pré-embauche à Casablanca'),
            array('id'=>11, 'title'=>'Développeur Symfony2', 'author'=>'Ghis', 'content'=>'Je cherche un développeur Symfony2 pour un projet ô combien intéressant')
        );

        return $this->render('APPlatformBundle:Advert:menu.html.twig',
            array(

src/Advertproject/PlatformBundleOLD/Resources/views/Advert/add.html.twig
{% extends "APPlatformBundle::layout.html.twig" %}

{% block title %}{% endblock %}

{% block platform_body %}

    <h2>Ajouter une annonce</h2>

    {{ include("APPlatformBundle:Advert:form.html.twig") }}

    <p>
        Attention : cette annonce sera automatiquement ajoutée sur la page d'accueil après validation.
    </p>

{% endblock %}

src/Advertproject/PlatformBundleOLD/Resources/views/Advert/delete.html.twig
{# src/Advert-Project/PlatformBundle/Resources/views/Advert/delete.html.twig #}

{% extends "APPlatformBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block platform_body %}

    <h2>Supprimer une annonce</h2>

    <p>
        Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
    </p>

    {# On met l'id de l'annonce dans la route de l'action du formulaire #}
    <form action="{{ path('ap_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('ap_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/Advertproject/PlatformBundleOLD/Resources/views/Advert/edit.html.twig
{% extends "APPlatformBundle::layout.html.twig" %}

{% block title %}Modifier une annonce - {{ parent() }}{% endblock %}

{% block platform_body %}
    <h2>Modifier une annonce</h2>
    {{ include('APPlatformBundle:Advert:form_edit.html.twig') }}

    <p>
        Vous éditez une annonce déjà existante, merci de ne pas changer l'esprit général d'annonce.
    </p>
    <p>
        <a href="{{ path('ap_platform_view', {'id':advert.id}) }}"><i class="glyphicon glyphicon-chevron-left"></i>Retour à l'annonce</a>
    </p>
{% endblock %}

src/Advertproject/PlatformBundleOLD/Resources/views/Advert/form.html.twig
<h3>Formulaire d'annonce</h3>

<div class="well">
    {{ form_start(form, {'attr': {'class':'form-horizontal'}}) }}
        {{ form_errors(form) }}
        <div class="form-group">
            {{ form_label(form.title, "Titre de l'annonce", {'label_attr':{'class':'col-sm-3 control-label'}}) }}
            {{ form_errors(form.title) }}
            <div class="col-sm-4">
                {{ form_widget(form.title, {'attr': {'class':'form-control'}}) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.content, "Contenu de l'annonce", {'label_attr':{'class':'col-sm-3 control-label'}}) }}
            {{ form_errors(form.content) }}
            <div class="col-sm-4">
                {{ form_widget(form.content, {'attr': {'class':'form-control'}}) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.published, "Publier l'annonce maintenant", {'label_attr':{'class':'col-sm-3 control-label'}}) }}
            {{ form_errors(form.published) }}
            <div class="col-sm-4">
                <div class="row"><br>
                    <div class="col-sm-12">{{ form_widget(form.published) }}</div>
                </div>

            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.image, "Sélectionnez une image", {'label_attr':{'class':'col-sm-3 control-label'}}) }}
            {{ form_errors(form.image) }}
            <div class="col-sm-4">
                {{ form_widget(form.image) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.categories, "Catégories", {'label_attr':{'class':'col-sm-3 control-label'}}) }}
            {{ form_errors(form.categories) }}
            <div class="col-sm-4">
                {{ form_widget(form.categories) }}
            </div>
        </div>

        {{ form_rest(form) }}
        <br><br><br>
        <div class="form-group">
            <div class="col-sm-3"></div>
            <div class="col-sm-4">
                <input type="submit" class="form-control btn btn-primary" value="Save" />

            </div>
        </div>


    {{ form_end(form) }}
</div>
{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
    $(document).ready(function() {
        // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
        var $container = $('div#advertproject_platformbundle_advert_categories');

        // On ajoute un lien pour ajouter une nouvelle catégorie
        var $addLink = $('<a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>');
        $container.append($addLink);

        // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
        $addLink.click(function(e) {
            addCategory($container);
            e.preventDefault(); // évite qu'un # apparaisse dans l'URL
            return false;
        });

        // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
        var index = $container.find(':input').length;

        // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
        if (index == 0) {
            addCategory($container);
        } else {
            // Pour chaque catégorie déjà existante, on ajoute un lien de suppression
            $container.children('div').each(function() {
                addDeleteLink($(this));
            });
        }

        // La fonction qui ajoute un formulaire Categorie
        function addCategory($container) {
            // Dans le contenu de l'attribut « data-prototype », on remplace :
            // - le texte "__name__label__" qu'il contient par le label du champ
            // - le texte "__name__" qu'il contient par le numéro du champ
            var $prototype = $($container.attr('data-prototype').replace(/__name__label__/g, 'Catégorie n°' + (index+1))
                    .replace(/__name__/g, index));

            // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
            addDeleteLink($prototype);

            // On ajoute le prototype modifié à la fin de la balise <div>
            $container.append($prototype);

            // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
            index++;
        }

        // La fonction qui ajoute un lien de suppression d'une catégorie
        function addDeleteLink($prototype) {
            // Création du lien
            $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

            // Ajout du lien
            $prototype.append($deleteLink);

            // Ajout du listener sur le clic du lien
            $deleteLink.click(function(e) {
                $prototype.remove();
                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                return false;
            });
        }
    });
</script>

src/Advertproject/PlatformBundleOLD/Resources/views/Advert/menu.html.twig

    <ul class="nav nav-pills nav-stacked" id="myTab">
        {% for advert in listAdverts %}
            <li>
                <a data-toggle="tab" href="{{ path('ap_platform_view', {'id':advert.id}) }}">{{ advert.title }}</a>
            </li>
            <div class="tab-content">
                <div class="tab-pane fade active in" id={{ advert.title }}>
                    {{ advert.content }}
                </div>
            </div>
        {% endfor %}

    </ul>


src/Advertproject/PlatformBundleOLD/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "APPlatformBundle::layout.html.twig" %}

{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block platform_body %}
    <div class="row" id="message" style="display: none;">
        <div class="col-sm-offset-3 col-sm-6 alert alert-success">
            {% for flashMessage in app.session.flashBag.get('notice') %}
                {{ flashMessage }} !
            {% endfor %}
        </div>
    </div>
    <br><br><br>
    <h2>{{ advert.title }}</h2>
    <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

    <div class="well row">
        <div class="col-sm-3">
            {% if advert.image is not null %}
                <img src="{{ asset(advert.image.uploadDir ~ '/' ~ advert.image.id ~ '.' ~ advert.image.url) }}" alt="{{ advert.image.alt }}">
            {% endif %}
        </div>
        <div class="col-sm-9">
            {{ advert.content }}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% if not advert.categories.empty %}
                <p>
                    Cette annonce est parue dans les catégories suivantes :
                    {% for category in advert.categories %}
                        {{ category.name }}{% if not loop.last %},{% endif %}
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>


    {% if listAdvertSkills|length > 0 %}
        <div>
            Cette annonce requiert les compétences suivantes :
            <ul>
                {% for advertSkill in listAdvertSkills  %}
                    <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="row">
        {#{% for application in listApplication %}#}
            <div class="col-sm-12">{#{{ application.content }}#}</div>
        {#{% endfor %}#}
    </div>

    <p>
        <a href="{{ path('ap_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <a href="{{ path('ap_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier l'annonce
        </a>
        <a href="{{ path('ap_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer l'annonce
        </a>
    </p>

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();

            function view_alert(){
                $("#message").css('display','block');
                $(".alert").show("slow").delay(5000).hide('slow');
            }
            setTimeout(view_alert, 2000);


        });
    </script>

{% endblock %}
